[package]
name = "nn-tornado-identification"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
micrograd-rs = "0.0.3"
